### ISSUE TITLE
Some feedback

### ISSUE THREAD

**Issue by kaiminchang** [yueranyuan/football_game_site#3]
1. Add number (1, 2) to the player's jersey (clarity)
2. Make "non-juking" enemies black, and "juking" enemies blue to denote that they have different behaviors (you can't earn juke points from non-juking enemies right)
3. The effect of foam finger wasn't clear until going into store (make a big +30 or something similar to juke cheers.
4. It's not clear when does the invisibility wears off. Make a count down hourglass or circle around the player?
5. Make a tailwind when the juking enemies juke?
6. You may want to remove "Menu" from the store as it starts over the game.
7. Similar to "StartInstruction", can you also output a "Debriefing" event
8. Flush a "Restart" that is missing in the following:

2015-06-13 19:44:28.297 Restart Experiment
2015-06-13 19:46:07.382 Easy    Experiment
2015-06-13 19:47:10.898 Lost    Experiment

**Comment by yueranyuan** [comment]
Did 2, 3, 6 (only in experiment mode), 7, and 8. Updated game on site
