### ISSUE TITLE
Change experiment from [3 min x 4] to [1.5 min x 8]

### ISSUE THREAD

**Issue by kaiminchang** [yueranyuan/football_game_site#6]
Change experiment from 3 minutes of Norm-Easy-Norm-Hard (or Norm-Hard-Norm-Easy) to
1.5 minutes of Norm-Easy-Norm-Hard-Norm-Hard-Norm-Easy (or variations like that)

Make sure there are equal number of easy and hard

**Comment by yueranyuan** [comment]
done
